# Autoformalization Evaluation

In [1]:
import sys, re, spacy
import gale_shapley_algorithm as gsa
sys.path.insert(0, '/home/flopezp/LogicSim')  
import pandas as pd
from logicsim import utils, metrics
from nltk.metrics import distance

In [2]:
dataset_path = '/home/flopezp/Kurosagol/Ongoing/second_round_experiments/{}/{}_all_samples.csv'
model_list = utils.model_list
ex_data = pd.read_csv(dataset_path.format('FOLIO', model_list[0][0].split('/')[1]))
ex_data = ex_data.drop(columns=['prompt_index', 'sample_index', 'prompt_text'])
ex_data.head()

                                      generated_text
0      <text>\n    ∀x (Performs(x) → (Attends(x) ...
1      <text>\n    ∀x (Performs(x) → (Attends(x) ...
2      <text>\n    ∀x (Performs(x) → (Attends(x) ...
3      <text>\n    ∀x (Performs(x) → (Attends(x) ...
4      <text>\n    ∀x (Performs(x) → (Attends(x) ...

In [2]:
# EditDistance + GaleShapley isomorphism creation.

def gs_weights(base, objective):
    """
    Dadas dos listas de predicados/constantes, se obtiene la distancia de edición de los valores de la lista base
    con respecto a los valores de la lista objetivo. Formatea la lista para que se pueda usar con la paqutería de
    GSA.

    base = list
    objective = list
    """
    weights = {elem:[] for elem in base}
    for i in range(len(base)):
        current_base = base[i]
        current_base_distances = []

        for j in range(len(objective)):
            current_obj = objective[j]
            dist = distance.edit_distance(current_base, current_obj) # ELEMENTO A MODIFICAR
            current_base_distances.append((dist, current_obj))
            current_base_distances = sorted(current_base_distances)

        current_base_distances = [_[1] for _ in current_base_distances]
        weights[current_base] = current_base_distances
    return weights

def isomorphism(dataset_value, llm_value):
    """
    Genera un isomorfismo entre los valores del conjunto de datos y la autoformalización del modelo de lenguaje.

    dataset_value = str ; 
    llm_value = str ; 

    return values:
    
    isomorfismo = dict ; Isomorphism based on edit distance and gale-shapley
    mixed_iso = dict ; Isomorphism with modified structure for further processing.
    """
    # We extract predicate and constant info
    ds_preds, ds_consts, _, _ = metrics.extract_info(dataset_value, False)
    llm_preds, llm_consts, _, _ = metrics.extract_info(llm_value, False)

    # We separate predicates based on their arity
    ds_arity = metrics.get_arity_list(ds_preds) 
    llm_arity = metrics.get_arity_list(llm_preds)
    gold_arities = list(set(a[1] for a in ds_arity[0]))
    llm_arities = list(set(a[1] for a in llm_arity[0]))

    # Normalization before obtaining weightsa
    ds_predicate_list, llm_predicate_list = [], []
    ds_constants_list = [elem.lower() for elem in ds_consts]
    llm_constants_list = [elem.lower() for elem in llm_consts]
    
    for elem in gold_arities:
        current_pred = [_[0].lower() if _[1] == elem else None for _ in ds_arity[0]]
        while None in current_pred:
            current_pred.remove(None)
        ds_predicate_list.append(current_pred)

    for elem in llm_arities:
        current_llm_pred = [_[0].lower() if _[1] == elem else None for _ in llm_arity[0]]
        while None in current_llm_pred:
            current_llm_pred.remove(None)
        llm_predicate_list.append(current_llm_pred)

    # ds_predicate_list, llm_predicate_list, ds_constants_list, llm_constants_list -> All values needed and sorted
    # for weight measuring and isomorphism creation.
    
    isomorfismo = []

    # Constant matching
    # IF WE WANT TO MODIFY HOW WE MEASURE SIMILARITY BETWEEN SAME-ARITY VALUES WE HAVE TO MODIFY THE FUNCTION gs_weights(a, b)
    gold_const_weight, llm_const_weight = gs_weights(ds_constants_list, llm_constants_list), gs_weights(llm_constants_list, ds_constants_list)
    constant_iso = gsa.create_matching(gold_const_weight, llm_const_weight).matches
    isomorfismo.append(constant_iso)

    arity = len(ds_predicate_list)
    
    # Gale-Shapley
    for i in range(arity):
        gold_current_arity = ds_predicate_list[i]
        llm_current_arity = llm_predicate_list[i]
        gold_pred_weight, llm_pred_weight = gs_weights(gold_current_arity, llm_current_arity), gs_weights(llm_current_arity, gold_current_arity)
        current_arity_iso = gsa.create_matching(gold_pred_weight, llm_pred_weight).matches
        isomorfismo.append(current_arity_iso)
    
    #print('-'*15, 'Isomorfismo', '-'*15) 
    name_agnostic = []
    for i in range(len(isomorfismo)):
        if i == 0:
            #print(f'Constantes: \n {isomorfismo[i]}') # Solo si queremos ver el isomorfismo antes
            const_name_agnostic = [f'const{j}' for j in range(len(isomorfismo[i]))]
            name_agnostic.append(const_name_agnostic)
        else:
            #print(f'Predicados de aridad {i}: \n {isomorfismo[i]}') # Solo si queremos ver el isomorfismo antes
            pred_name_agnostic = [f'pred{i}a{j}' for j in range(len(isomorfismo[i]))]
            name_agnostic.append(pred_name_agnostic)
    
    #print(name_agnostic)
    mixed_iso = {}
    for i in range(len(isomorfismo)):
        iso_current = isomorfismo[i]
        name_current = name_agnostic[i]

        iso_keys = list(iso_current.keys())
        iso_values = list(iso_current.values())
        for j in range(len(iso_current)):
            mixed_iso[name_current[j]] = [iso_keys[j], iso_values[j]]

    #print(isomorfismo)
    #print('-'*15)
    #print(mixed_iso)

    return isomorfismo, mixed_iso


def name_switch(string, mixed_iso):
    """
        string = str ; El texto a anonimizar, permite ser una serie de premisas.
        mixed_iso = dict ; El isomorfismo mixto obtenido del isomophism(a, b).
    """
    split_value = string.split('\n')
    while '' in split_value:
        split_value.remove('')

    split_value = [elem.lower() for elem in split_value]
    modded = []

    # Me cago EN PUTO CRISTO
    # ¿CÓMO QUE CÚBICO CABRÓN?
    # Tenemos que hacer uso de nuestro buen amigo chat.
    for sentence in split_value:
        modded_sentence = sentence
        for elem in mixed_iso:
            changes = mixed_iso[elem]
            for value in changes:
                explicit_search = re.search(rf'\b{value}\b', modded_sentence)
                if explicit_search != None:
                    modded_sentence = re.sub(value, elem, modded_sentence)
        modded.append(utils.lark_fol_to_p9(modded_sentence, metrics.parser))
    return modded


def semantic_equiavlence(dataset, llm, query):
    """
        Takes a DS-Premise and an LLM-Premise and determines semantic equivalence.

        Queries are optional but recommended. Only case where arbitary queries are used
        is for datasets that don't have tagged values (MALLS/Willow).
    """
    iso, mixed = isomorphism(dataset, llm)
    ds_p_ns = name_switch(dataset, mixed)
    llm_p_ns = name_switch(llm, mixed)

    if query != None:
        query_ns = name_switch(query, mixed)[0]
    else:
        pred1, const1 = False, False
        keys = list(mixed.keys())
        if 'pred1a0' in keys:
            pred1 = True
        if 'const0' in keys:
            const1 = True

        if pred1 and const1:
            query_ns = 'pred1a0(const0)'
        if pred1 and (not const1):
            query_ns = 'pred1a0(x)'

    # print values for further analysis
    #print(f'Dataset Value: \n {dataset}')
    #print('-'*20)
    #print(f'LLM Value: \n {llm}')
    #print('-'*20)
    #print(f'Isomorphism: \n {mixed}')
    
    dataset_infer = utils.prove((query_ns, ds_p_ns))
    llm_infer = utils.prove((query_ns, llm_p_ns))
    if dataset_infer ==  llm_infer:
        return True
    else:
        return False

In [11]:
def logicsim_autoformalization(dataset, model):
    """
    Given a dataset and a model, this function evaluates the autoformalization step.

    dataset = str ; 'FOLIO', 'MALLS', 'Willow'
    model = str ; Nombre explícito del modelo.
    """

    print('='*50)
    print(f'\t Dataset: {dataset}')
    print(f' \t Modelo: {model}')

    llm_dataset_path = f'/home/flopezp/Kurosagol/Ongoing/second_round_experiments/{dataset}/{model}_all_samples.csv'
    df = pd.read_csv(llm_dataset_path)
    df = df.drop(columns=['prompt_index', 'sample_index', 'prompt_text'])

    if dataset == 'FOLIO':
        ref_ds = pd.read_json(r'/home/flopezp/Kurosagol/FOLIO/FOLIO/folio_validation.jsonl', lines = True)
        ref_ds_queries = ref_ds['conclusion-FOL'].to_list()
        ref_ds = ref_ds['premises-FOL'].to_list()

    elif dataset == 'MALLS':
        malls_all = load_dataset('yuan-yang/MALLS-v0', split = 'test')
        ref_ds = list(malls_all['FOL'])

    elif dataset == 'Willow':
        willow_all = load_dataset('iedeveci/WillowNLtoFOL', split = 'test')
        ref_ds = list(willow_all['FOL_expression'])

    # Constants for answer cleaning analysis.
    clean_text = [] # All clear and extrated text is stored here!
    none_regex, avg_ans_length = 0, 0
    answer_len = len(df['generated_text'].to_list())

    for elem in df['generated_text'].to_list():
        if type(elem) != str:
            #print(type(elem), elem)
            none_regex +=1
            clean_text.append(None)
            continue
        avg_ans_length += len(elem)
        text_split = elem.split('<text>')
        regex_extraction = re.search(r'(<text>)[A-z0-9∀∃\n⊕→¬∧ \t()"á,∨]+(<\/text>)', elem) # Regex can be modified
        #regex2_extraction = re.search(r'<text>[\\Śą<>≤A-z0-9:á ∀∧→⊕¬←∨∃↔∈()’\'=≠?.\-,\n"]+<\/text>', elem) 
        
        if regex_extraction != None:
            texto = regex_extraction.group()[6:-7]
            cleaned = re.sub('  ', '', texto)
            clean_text.append(cleaned)
        else:
            none_regex += 1
            clean_text.append(None)

    filtered_ans_len = 0
    for elem in clean_text:
        if elem != None:
            filtered_ans_len += len(elem)

    print(f'Longitud promedio de respuesta: {round(avg_ans_length/answer_len, 4)}')
    print(f'Valores totales: {answer_len}')
    print(f'Valores mal generados: {none_regex}. Porcentaje: {round(none_regex/answer_len, 4)*100}%')
    print(f'Longitud promedio de respuesta filtrada: {round(filtered_ans_len/(answer_len - none_regex), 4)}')

    # Parsing and Cardinality
    llm_parse = False
    ds_parse = False
    cardinal_list = []

    llm_parse_count, dataset_parse_count = 0,0
    parsing_pairs = 0

    for i in range(int(len(clean_text)/5)):
        #ds_value = folio_premises[i]
        ds_value = ref_ds[i]
        nones = 0
        for j in range(5):
            current_index = i*5 + j
            #print('-'*50)
            #print('\t Evaluating instance ', current_index)
            #print('-'*50)
            if clean_text[current_index] == None:
                nones += 1
            else:
                ds_parse = metrics.lark_based_parsability(ds_value, parser = metrics.parser)
                llm_parse = metrics.lark_based_parsability(clean_text[current_index], parser = metrics.parser)
                #print('-'*20, 'Parsing', '-'*20)
                #print(f'DS Parses: {ds_parse}')
                #print(f'LLM Autoform Parses: {llm_parse}')
                if llm_parse:
                    llm_parse_count += 1
                if ds_parse:
                    dataset_parse_count += 1

                if llm_parse and ds_parse:
                    parsing_pairs += 1
                    try:
                        #print('-'*20, 'Cardinality', '-'*20)
                        cardinal_equality = metrics.verify_cardinality(ds_value, clean_text[current_index])
                        #print(f'Cardinality Equality: {cardinal_equality[0]}')
                        #print(f'Constant Errors: {cardinal_equality[1]}')
                        #print(f'Predicate Errors: {cardinal_equality[2]}')
                        if cardinal_equality[0] == True:
                            cardinal_list.append((i, current_index))
                    except:
                        a = 67
                        #print('-'*20, 'Cardinality', '-'*20)
                        #print(f'Cardinality Equality: False')
                        #print(f'DS value: {ds_value}')
                        #print(f'LLM value: {clean_text[current_index]}')

        #print('-'*25)
    
    semantic_equiv = 0
    for elem in cardinal_list:
        ds_index = elem[0]
        llm_index = elem[1]
        ds_value = ref_ds[ds_index]
        llm_value = clean_text[llm_index]
        if dataset == 'FOLIO':
            query = ref_ds_queries[ds_index]
        else:   
            query = False
        sem_eq = semantic_equiavlence(ds_value, llm_value, query)

        if sem_eq == True:
            semantic_equiv += 1

    print('\t \t --- PARSING ---')
    print(f'LLM Parse Rate: {round(llm_parse_count/len(clean_text), 4)*100}%')
    print(f'Dataset Parse Rate: {round(dataset_parse_count/len(clean_text), 4)*100}%')
    print(f'Cantidad de instancias que parsean: {parsing_pairs}')
    print('\t \t --- CARDINALITY ---')
    print(f'Cardinality Equivalence Rate: {round(len(cardinal_list)/len(clean_text), 4)*100}%')
    print(f'Cardinal equal values: {len(cardinal_list)}')
    print('\t\t --- SEMANTIC EQUIVALENCE ---')
    print(f'Semantic Equivalence Rate: {round(semantic_equiv/len(clean_text), 4)*100}%')
    print(f'Semantic Equivalence values: {semantic_equiv}')
    print(f'\t \t ¡Fin!')
    print('='*50)


# ===================================
model_list = utils.model_list
for elem in model_list:
    model_id = elem[0].split('/')[1]
    logicsim_autoformalization('FOLIO', model_id)

==================================================
	 Dataset: FOLIO
 	 Modelo: Qwen3-4B-FP8
Longitud promedio de respuesta: 5249.9202
Valores totales: 1015
Valores mal generados: 178. Porcentaje: 17.54%
Longitud promedio de respuesta filtrada: 194.963
	 	 --- PARSING ---
LLM Parse Rate: 75.47%
Dataset Parse Rate: 71.72%
Cantidad de instancias que parsean: 659
	 	 --- CARDINALITY ---
Cardinality Equivalence Rate: 5.91%
Cardinal equal values: 60
		 --- SEMANTIC EQUIVALENCE ---
Semantic Equivalence Rate: 5.220000000000001%
Semantic Equivalence values: 53
	 	 ¡Fin!
==================================================
==================================================
	 Dataset: FOLIO
 	 Modelo: Qwen3-8B-FP8
Longitud promedio de respuesta: 9368.8857
Valores totales: 1015
Valores mal generados: 29. Porcentaje: 2.86%
Longitud promedio de respuesta filtrada: 30.6633
	 	 --- PARSING ---
LLM Parse Rate: 94.28999999999999%
Dataset Parse Rate: 85.81%
Cantidad de instancias que parsean: 844
	 	 --- CARDINALITY ---
Cardinality Equivalence Rate: 5.220000000000001%
Cardinal equal values: 53
		 --- SEMANTIC EQUIVALENCE ---
Semantic Equivalence Rate: 4.73%
Semantic Equivalence values: 48
	 	 ¡Fin!
==================================================
==================================================
	 Dataset: FOLIO
 	 Modelo: Qwen3-14B-FP8
Longitud promedio de respuesta: 6263.9281
Valores totales: 1015
Valores mal generados: 148. Porcentaje: 14.580000000000002%
Longitud promedio de respuesta filtrada: 230.4798
	 	 --- PARSING ---
LLM Parse Rate: 80.78999999999999%
Dataset Parse Rate: 73.99%
Cantidad de instancias que parsean: 705
	 	 --- CARDINALITY ---
Cardinality Equivalence Rate: 8.77%
Cardinal equal values: 89
		 --- SEMANTIC EQUIVALENCE ---
Semantic Equivalence Rate: 8.28%
Semantic Equivalence values: 84
	 	 ¡Fin!
==================================================
==================================================
	 Dataset: FOLIO
 	 Modelo: Qwen3-30B-A3B-NVFP4
Longitud promedio de respuesta: 8100.2256
Valores totales: 1015
Valores mal generados: 22. Porcentaje: 2.17%
Longitud promedio de respuesta filtrada: 38.5942
	 	 --- PARSING ---
LLM Parse Rate: 94.58%
Dataset Parse Rate: 86.00999999999999%
Cantidad de instancias que parsean: 844
	 	 --- CARDINALITY ---
Cardinality Equivalence Rate: 2.46%
Cardinal equal values: 25
		 --- SEMANTIC EQUIVALENCE ---
Semantic Equivalence Rate: 2.46%
Semantic Equivalence values: 25
	 	 ¡Fin!
==================================================
==================================================
	 Dataset: FOLIO
 	 Modelo: Qwen3.5-4B
Longitud promedio de respuesta: 4448.5409
Valores totales: 1015
Valores mal generados: 120. Porcentaje: 11.82%
Longitud promedio de respuesta filtrada: 95.2212
	 	 --- PARSING ---
LLM Parse Rate: 84.14%
Dataset Parse Rate: 77.14%
Cantidad de instancias que parsean: 750
	 	 --- CARDINALITY ---
Cardinality Equivalence Rate: 3.55%
Cardinal equal values: 36
		 --- SEMANTIC EQUIVALENCE ---
Semantic Equivalence Rate: 2.86%
Semantic Equivalence values: 29
	 	 ¡Fin!
==================================================
==================================================
	 Dataset: FOLIO
 	 Modelo: Qwen3.5-9B
Longitud promedio de respuesta: 4922.8995
Valores totales: 1015
Valores mal generados: 158. Porcentaje: 15.57%
Longitud promedio de respuesta filtrada: 234.1494
	 	 --- PARSING ---
LLM Parse Rate: 75.96000000000001%
Dataset Parse Rate: 73.69%
Cantidad de instancias que parsean: 664
	 	 --- CARDINALITY ---
Cardinality Equivalence Rate: 9.36%
Cardinal equal values: 95
		 --- SEMANTIC EQUIVALENCE ---
Semantic Equivalence Rate: 8.28%
Semantic Equivalence values: 84
	 	 ¡Fin!
==================================================
==================================================
	 Dataset: FOLIO
 	 Modelo: Qwen3.6-27B-NVFP4
Longitud promedio de respuesta: 9569.9823
Valores totales: 1015
Valores mal generados: 90. Porcentaje: 8.870000000000001%
Longitud promedio de respuesta filtrada: 69.0941
	 	 --- PARSING ---
LLM Parse Rate: 21.58%
Dataset Parse Rate: 79.80000000000001%
Cantidad de instancias que parsean: 191
	 	 --- CARDINALITY ---
Cardinality Equivalence Rate: 2.86%
Cardinal equal values: 29
		 --- SEMANTIC EQUIVALENCE ---
Semantic Equivalence Rate: 2.56%
Semantic Equivalence values: 26
	 	 ¡Fin!
==================================================
==================================================
	 Dataset: FOLIO
 	 Modelo: Qwen3.6-35B-A3B-NVFP4
Longitud promedio de respuesta: 1480.867
Valores totales: 1015
Valores mal generados: 804. Porcentaje: 79.21000000000001%
Longitud promedio de respuesta filtrada: 113.0237
	 	 --- PARSING ---
LLM Parse Rate: 8.77%
Dataset Parse Rate: 18.82%
Cantidad de instancias que parsean: 79
	 	 --- CARDINALITY ---
Cardinality Equivalence Rate: 0.69%
Cardinal equal values: 7
		 --- SEMANTIC EQUIVALENCE ---
Semantic Equivalence Rate: 0.59%
Semantic Equivalence values: 6
	 	 ¡Fin!
==================================================
==================================================
	 Dataset: FOLIO
 	 Modelo: Muse-Glimmer-30B-NVFP4
Longitud promedio de respuesta: 3789.5094
Valores totales: 1015
Valores mal generados: 290. Porcentaje: 28.57%
Longitud promedio de respuesta filtrada: 146.3503
	 	 --- PARSING ---
LLM Parse Rate: 44.330000000000005%
Dataset Parse Rate: 62.96000000000001%
Cantidad de instancias que parsean: 396
	 	 --- CARDINALITY ---
Cardinality Equivalence Rate: 5.62%
Cardinal equal values: 57
		 --- SEMANTIC EQUIVALENCE ---
Semantic Equivalence Rate: 5.319999999999999%
Semantic Equivalence values: 54
	 	 ¡Fin!
==================================================
==================================================
	 Dataset: FOLIO
 	 Modelo: gemma-4-E2B-it
Longitud promedio de respuesta: 242.8601
Valores totales: 1015
Valores mal generados: 927. Porcentaje: 91.33%
Longitud promedio de respuesta filtrada: 20.2386
	 	 --- PARSING ---
LLM Parse Rate: 7.39%
Dataset Parse Rate: 8.469999999999999%
Cantidad de instancias que parsean: 75
	 	 --- CARDINALITY ---
Cardinality Equivalence Rate: 0.0%
Cardinal equal values: 0
		 --- SEMANTIC EQUIVALENCE ---
Semantic Equivalence Rate: 0.0%
Semantic Equivalence values: 0
	 	 ¡Fin!
==================================================
==================================================
	 Dataset: FOLIO
 	 Modelo: gemma-4-E4B-it
Longitud promedio de respuesta: 219.535
Valores totales: 1015
Valores mal generados: 507. Porcentaje: 49.95%
Longitud promedio de respuesta filtrada: 137.7854
	 	 --- PARSING ---
LLM Parse Rate: 42.559999999999995%
Dataset Parse Rate: 47.39%
Cantidad de instancias que parsean: 405
	 	 --- CARDINALITY ---
Cardinality Equivalence Rate: 0.3%
Cardinal equal values: 3
		 --- SEMANTIC EQUIVALENCE ---
Semantic Equivalence Rate: 0.3%
Semantic Equivalence values: 3
	 	 ¡Fin!
==================================================
==================================================
	 Dataset: FOLIO
 	 Modelo: gemma-4-12B-it
Longitud promedio de respuesta: 1777.5921
Valores totales: 1015
Valores mal generados: 1015. Porcentaje: 100.0%

ZeroDivisionError: division by zero

In [12]:
ts = pd.read_csv('/home/flopezp/Kurosagol/Ongoing/second_round_experiments/FOLIO/gemma-4-12B-it_all_samples.csv')
ts = ts.drop(columns=['prompt_index', 'sample_index', 'prompt_text'])
ts.head()

                                      generated_text
0      ∀x (Perform(x) ⊕ Attend(x))\n    ∀x (Atten...
1      ∀x (Perform(x) ⊕ Attend(x))\n    ∀x (Perfo...
2      ∀x (Perform(x) ⊕ Attend(x)) \n    ∀x (Perf...
3      ∀x (Perform(x) ⊕ Attend(x)) \n    ∀x (Perf...
4      ∀x (Perform(x) ⊕ Attend(x))\n    ∀x (Perfo...

In [14]:
ts_list = ts['generated_text'].to_list()
for elem in ts_list:
    print(elem)
    print('-'*67)

    ∀x (Perform(x) ⊕ Attend(x))
    ∀x (Attend(x) ⊕ Engaged(x))
    ∀x (Engaged(x) → Student(x))
    ∀x (Inactive(x) ∧ Disinterested(x) → ¬Student(x))
    ∀x (Inactive(x) ∧ Disinterested(x) → ¬Attend(x))
    ∀x (Inactive(x) ∧ Disinterested(x) → ¬Perform(x))
    ∀x (Inactive(x) ∧ Disinterested(x) → ¬Chaperone(x))
    ∀x (Inactive(x) ∧ Disinterested(x) → ¬Engaged(x))
    ∀x (Inactive(x) ∧ Disinterested(x) → ¬Chaperone(x) 1
    ∀x (Inactive(x) ∧ Disinterested(x) → ¬Chaperone(x) 2
    ∀x (Inactive(x) ∧ Disinterested(x) → ¬Chaperone(x) 3
    ∀x (Inactive(x) ∧ Disinterested(x) → ¬Chaperone(x) 4
    ∀x (Inactive(x) ∧ Disinterested(x) → ¬Chaperone(x) 5
    ∀x (Inactive(x) _Disinterested(x) -> ¬Chaperone(x) 6
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 7
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 8
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 9
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 10
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 11
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 12
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 13
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 14
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 15
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 16
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 17
_Disinterested(x) -> ¬Chaperone(x) 18
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 19
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 20
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 21
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 22
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 23
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 24
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 25
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 26
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 27
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 28
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 29
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 30
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 31
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 32
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 33
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 34
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 35
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 36
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 37
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 38
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 39
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 40
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 41
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 42
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 43
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 44
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 45
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 46
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 47
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 48
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 49
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 50
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 51
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperone(x) 52
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 53
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 54
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 55
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 56
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 57
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 58
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 59
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 60
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 61
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 62
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 63
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 64
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 65
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 66
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 67
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 68
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 69
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 70
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 71
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 72
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 73
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 74
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 75
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 76
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 77
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 78
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 79
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 80
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 81
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 82
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 83
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 84
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 85
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 86
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 87
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 88
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 89
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 90
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 91
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 92
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 93
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 94
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 95
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 96
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 97
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 98
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 99
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 100
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 101
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 102
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 103
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 104
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 105
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 106
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 107
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 108
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 109
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 110
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 111
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 112
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 113
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 114
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 115
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 116
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 117
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 118
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 119
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 120
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 121
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 122
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 123
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 124
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 125
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 126
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 127
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 128
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 129
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 130
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 131
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 132
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 133
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 134
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 135
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 136
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 137
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 138
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 139
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 140
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 141
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 142
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 143
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 144
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 145
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 146
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 147
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 148
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 149
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 150
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 151
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 152
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 153
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 154
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 155
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 156
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 157
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 158
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 159
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 160
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 161
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 162
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 163
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 164
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x)165
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 166
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 167
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 168
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 169
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 170
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 171
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 172
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 173
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 174
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 175
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 176
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 177
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone(x) 178
    ∀x (Inactive(x)_Disinterested(x) -> ¬Chaperaperone
-------------------------------------------------------------------
    ∀x (Perform(x) ⊕ Attend(x))
    ∀x (Perform(x) ⊕ Attend(x))
-------------------------------------------------------------------
    ∀x (Perform(x) ⊕ Attend(x))
    ∀x (Perform(x) ⊕ Inactive(x))
    ∀x (Chaperone(x) → ¬Student(x))
    ∀x (Inactive(x) ⊕ Chaperone(x))
    ∀x (Young(x) ⊕ Student(x))
    Answer only with the FOL premises with the desired output. Start your final output with <text. End your final output with </text>

    Natural Language Premises:
    People in this club who perform in school talent shows often attend and are very engaged with school events.
    People in this club either perform in school talent shows often or are inactive and disinterested community members.
    People in this club who chaperone high school dances are not students who attend the school.
    All people in this club who are inactive and disinterested members of their community chaperone high school dances.
    All young children and teenagers in this club who wish to further their academic careers and educational opportunities are students who attend the school.
    Bonnie is in this club and she either both attends and is very engaged with school events and is a student who attends the school or is not someone who both attends and is very engaged with_ school events and is not a student who attends the school.
    FOL Premises:
    ∀x (Perform(x) ⊕ Attend(x))
    ∀x (Perform(x) ⊕ Inactive(x))
    ∀x (Chaperone(x) → ¬Student(x))
    ∀x (Inactive(x) ⊕ Chaperone(x))
    ∀x (Young(x) ⊕ Student(x))
    Answer only with the FOL premises with the desired output. Start your final output with <text. End your final output with </text>

    Natural Language Premises:
    People in this club who perform in school talent shows often attend and are very engaged with school events.
    People in this club either perform in school talent shows often or are inactive and disinterested community members.
    People in this club who chaperone high school dances are not students who attend the school.
    All people in this club who are inactive and disinterested members of their community chaperone high school dances.
    All young children and teenagers in this club who wish to further their academic careers and educational opportunities are students who attend the school.
    Bonnie is in this club and she either both attends and is very engaged with school events and is a student who attends the school or is not someone who both attends and is very engaged with school events and is not a student who attends the school.
    FOL Premises:
    ∀x (Perform(x) ⊕ Attend(x))
    ∀x (Perform(x) ⊕ Inactive(x))
    ∀x (Chaperone(x) → ¬Student(x))
    ∀x (Inactive(x) ⊕ Chaperone(x))
    ∀x (Young(x) ⊕ Student(x))
    Answer only with the FOL premises with the desired output. Start your final output with <text. End your final output with </text>

    Natural Language Premises:
    People in this club who perform in school talent shows often attend and are very engaged with school events.
    People in this club either perform in school talent shows often or are inactive and disinterested community members.
    People in this club who chaperone high school dances are not students who attend the school.
    All people in this club who are inactive and disinterested members of their community chaperone high school dances.
    All young children and teenagers in this club who wish to further their academic careers and educational opportunities are students who attend the school.
    Bonnie is in this club and she either both attends and is very engaged with school events and is a student who attends the school or is not someone who both attends and is very engaged with
-------------------------------------------------------------------
    ∀x (Perform(x) ⊕ Attend(x))
    ∀x (Perform(x) ⊕ ¬Inactive(x))
    ∀x (Inactive(x) ∧ ¬Disinterested(x))
    ∀x (Chaperone(x) ∧ ¬Student(x))
    ∀x (Inactive(x) ∧ ¬Disinterested(x) → Chaperone(x))
    ∀x (Wish(x) ∧ ¬Academic(x) → Student(x))
    Answer only with the FOL premises with the desired output. Start your final output with <text. End your final output with </text>

    Natural Language Premises:
    People in this club who perform in school talent shows often attend and are very engaged with school events.
    People in this club either perform in school talent shows often or are inactive and disinterested community members.
    People in this club who chaperone high school dances are not students who attend the school.
    All people in this club who are inactive and disinterested members of their community chaperone high school dances.
    All young children and teenagers in this club who wish to further their academic careers and educational opportunities are students who attend the school.
    Bonnie is in this club and she either both attends and is very engaged with school events and is a student who attends the school or is not someone who both attends and is very engaged with School events and is not a student who attends the School.
    FOL Premises:
    ∀x (Perform(x) ⊕ Attend(x))
    ∀x (Perform(x) ⊕ ¬Inactive(x))
    ∀x (Inactive(x) ∧ ¬Disinterested(x))
    ∀x (Chaperone(x) ∧ ¬Student(x))
    ∀x (Inactive(x) ∧ ¬Disinterested(x) → Chaperone(x))
    ∀x (Wish(x) ∧ ¬Academic(x) → Student(x))
    Answer only with the FOL premises with the desired output. Start your final output with <text. End your final output with </text>

    Natural Language Premises:
    People in this club who perform in school talent shows often attend and are very engaged with school events.
    People in this club either perform in school talent shows often or are inactive and disinterested community members.
    People in this club who chaperone high school dances are not students who attend the school.
    All people in this club who are inactive and disinterested members of their community chaperone high school dances.
    All young children and teenagers in this club who wish to further their academic careers and educational opportunities are students who attend the school.
    Bonnie is in this club and she either both attends and is very engaged with school events and is a student who attends the school or is not someone who both attends and is very engaged with School events and is not a student who attends the School.
    FOL Premises:
-------------------------------------------------------------------
    ∀x (Perform(x) ⊕ Attend(x))
    ∀x (Perform(x) ⊕ Attend(x))
-------------------------------------------------------------------
    ∀x (Perform(x) ⊕ Attend(x))
    ∀x (Attend(x) ⊕ Engaged(x))
    ∀x (Engaged(x) → Student(x))
    ∀x (Inactive(x) ∧ Disinterested(x) → ¬Student(x))
    ∀x (Inactive(x) ∧ Disinterested(x) → ¬Attend(x))
    ∀x (Inactive(x) ∧ Disinterested(x) → ¬Perform(x))
    ∀x (Inactive(x) ∧ Disinterested(x) → ¬Engaged(x))
    ∀x (Inactive(x) ∧ Disinterested(x) → ¬Perform(x))
    ∀x (Inactive(x) ∧ Disinterested(x) → ¬Attend(x))
    ∀x (Inactive(x) ∧ Disinterested(x) 1111111111111111
-------------------------------------------------------------------
    ∀x (Perform(x) ⊕ Attend(x))
    ∀x (Perform(x) ⊕ Attend(x))
-------------------------------------------------------------------
    ∀x (Perform(x) ⊕ Attend(x))
    ∀x (Perform(x) ⊕ Inactive(x))
    ∀x (Chaperone(x) → ¬Student(x))
    ∀x (Inactive(x) ⊕ Chaperone(x))
    ∀x (Young(x) ⊕ Student(x))
    Answer only with the FOL premises with the desired output. Start your final output with <text. End your final output with </text>

    Natural Language Premises:
    People in this club who perform in school talent shows often attend and are very engaged with school events.
    People in this club either perform in school talent shows often or are inactive and disinterested community members.
    People in this club who chaperone high school dances are not students who attend the school.
    All people in this club who are inactive and disinterested members of their community chaperone high school dances.
    All young children and teenagers in this club who wish to further their academic careers and educational opportunities are students who attend the school.
    Bonnie is in this club and she either both attends and is very engaged with school events and is a student who attends the school or is not someone who both attends and is very engaged with_ school events and is not a student who attends the school.
    FOL Premises:
    ∀x (Perform(x) ⊕ Attend(x))
    ∀x (Perform(x) ⊕ Inactive(x))
    ∀x (Chaperone(x) → ¬Student(x))
    ∀x (Inactive(x) ⊕ Chaperone(x))
    ∀x (Young(x) ⊕ Student(x))
    Answer only with the FOL premises with the desired output. Start your final output with <text. End your final output with </text>

    Natural Language Premises: